* Homework 5
** Interface
*** Debug interface
*** This is a debugging version ***\n
Unit Test Case 1: Ask no question. The program should give a warning
message.\n

Unit Test Case 2.1: Ask 1 question in the linked list. The tester enters an
incorrect answer.\n
Case 2.1 passed...

Unit Test Case 2.2: Ask 1 question in the linked list. The tester enters a
correct answer.
Case 2.2 passed...

Unit Test Case 3: Ask all the questions of the last trivia in the linked list.
...

Unit Test Case 4: Ask five questions in the linked list.

*** End of the Debugging Version ***

*** Welcome to Austin Minor's trivia quiz game ***
Enter a question:
Enter an answer:
Enter award points:
Continue? (Yes/No)
...

*** Thank you for playing the trivia quiz game. Goodbye! ***

** Structure
struct TriviaNode {
   TriviaNode* next_question;
   int amount;
   string question;
   string answer;
};

** Sample questions
How long was the shortest war on record? (Hint: how many minutes)
38
100

What was Bank of America's original name? (Hint: Bank of Italy or Bank of
Germany)?
Bank of Italy
50

What is the best-selling video game of all time? (Hint: Call of Duty or Wii
Sports)?
Wii Sports
20
